#BASH COLOURS

COLOUR_PREFIX="\033[1;"
COLOUR_SUFFIX="m"



CLR_CYAN=${COLOUR_PREFIX}36${COLOUR_SUFFIX}
CLR_GREEN=${COLOUR_PREFIX}32${COLOUR_SUFFIX}
CLR_ERROR=${COLOUR_PREFIX}31${COLOUR_SUFFIX}
CLR_INFO=${COLOUR_PREFIX}94${COLOUR_SUFFIX}
CLR_WARN=${COLOUR_PREFIX}33${COLOUR_SUFFIX}
CLR_END=${COLOUR_PREFIX}0${COLOUR_SUFFIX}
CLR_MAGENTA=${COLOUR_PREFIX}35${COLOUR_SUFFIX}


if [[ ! -z DISPLAY_HELP ]]; then
  echo ""
  echo -e ${CLR_INFO} Set Colours:
  echo -e ${CLR_CYAN} CYAN ${CLR_GREEN} GREEN ${CLR_ERROR} ERROR ${CLR_INFO} INFO ${CLR_WARN} WARN ${CLR_MAGENTA} MAGENTA ${CLR_END} [ColourEnd]
  echo ""
fi




